services:
  mysql:
    image: mysql:8.4.3
    ports:
      - 3306:3306
    volumes_from:
      - dbdata
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: development

  dbdata:
    image: tianon/true
    volumes:
      - /var/lib/mysql